project:
  type: book
  output-dir: docs

book:
  title: "Engineering Mathematics"
  author: "Kee-Youn Yoo"
  date: "2/28/2024"
  search: true
  cover-image: SeoulTech.png
  chapters:
    - index.qmd
    - ch_01_introduction_to_differential_equations.qmd
    - ch_02_First-Order_Differential_Equations.qmd
    - ch_03_Higher-Order_Differential_Equations.qmd
    - ch_04_The_Laplace_Transform.qmd
    - ch05_Series_Solutions_of_Linear_Differential_Equations.qmd
    # - references.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



