project:
  type: book
  output-dir: docs

book:
  title: "Engineering Mathematics"
  author: "Kee-Youn Yoo"
  date: "3/6/2024"
  search: true
  cover-image: SeoulTech.png
  chapters:
    - index.qmd
    - ch_01_Introduction_to_Differential_Equations_X.qmd
    - ch_02_First-Order_Differential_Equations.qmd
    - ch_03_Higher-Order_Differential_Equations.qmd
    - ch_04_The_Laplace_Transform.qmd
    - ch_05_Series_Solutions_of_Linear_Differential_Equations.qmd
    - ch_08_Matrices.qmd
    - ch_10_Systems_of_Linear_Differential_Equations.qmd
    # - references.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo

  pdf:
    documentclass: scrreprt