# Matrices {#sec-8}

## Matrix Algebra {#sec-8-1}

* A **matrix** is any rectangular array of numbers or functions

  $$\begin{pmatrix}
    a_{11} & a_{12} & \cdots & a_{1n}\\ 
    a_{21} & a_{22} & \ddots & a_{2n} \\ 
    \vdots & \ddots & \ddots & \vdots \\ 
    a_{m1} & a_{m2} & \cdots & a_{mn}
  \end{pmatrix}$$ 
   
  * The numbers or functions in the array are **entries** or **elements**
  * An $n \times n$ matrix  is a **square** matrix of **order $n$**

* **Column** and **row vectors** are $n \times 1$ and $1 \times n$ matrices

  $$
  \begin{pmatrix}
    a_1\\ 
    a_2\\ 
    \vdots\\ 
    a_n
  \end{pmatrix},\;
  \begin{pmatrix}
    a_1 & a_2 & \cdots & a_n
  \end{pmatrix}  
  $$

* **Equality of Matrices** 

  $$
  \begin{aligned}
   \mathbf{A} = \left(a_{ij}\right)_{m \times n} \; \text{ and } \;&\mathbf{B} = \left(b_{ij}\right)_{m \times n} \;\text{ are equal } \\[5pt]
   \text{ if } a_{ij}=b_{ij} \;&\text{ for each } i \text{ and } j
   \end{aligned}$$

* **Matrix Addition**

  $$\mathbf{A} +\mathbf{B} = \left(a_{ij} +b_{ij}\right)_{m \times n}$$

* **Scalar Multiplication**

  $$k\mathbf{A} = \left(ka_{ij}\right)_{m \times n}$$

* **Properties of Matrix Addition and Scalar Multiplication**

  Suppose $\mathbf{A}$, $\mathbf{B}$, and $\mathbf{C}$ are $m \times n$ matrices and $k_1$ and $k_2$ are scalars. Then

  $$
  \begin{aligned}
    \mathbf{A} +\mathbf{B} &= \mathbf{B} +\mathbf{A} \\ 
    \mathbf{A} +\left(\mathbf{B} +\mathbf{C}\right) &= \left(\mathbf{A} +\mathbf{B}\right) +\mathbf{C} \\
    \left(k_1 k_2\right)\mathbf{A} &= k_1 \left(k_2\mathbf{A}\right) \\
    k_1\left(\mathbf{A} +\mathbf{B}\right)&=k_1\mathbf{A} +k_1\mathbf{B} \\
    \left(k_1 +k_2\right)\mathbf{A} &= k_1 \mathbf{A} +k_2\mathbf{A}  
  \end{aligned}$$

* **Matrix multiplication** 
  
  $$\mathbf{A}\mathbf{B}=\left(\sum_{k=1}^p a_{ik} b_{kj}\right)_{m \times n}$$
  
  where $\mathbf{A}$ is an $m \times p$ matrix, $~\mathbf{B}$ is a $p \times n$ matrix, and
  $~\mathbf{A}\mathbf{B}$ is the $m \times n$ matrix
  
  * In general, $~\mathbf{A}\mathbf{B}\neq\mathbf{B}\mathbf{A}$
  
  * **Associative Law:** $~\mathbf{A}\left(\mathbf{B}\mathbf{C}\right)=\left(\mathbf{A}\mathbf{B}\right)\mathbf{C}$ 
  
  * **Distributive Law:** $~\mathbf{A}\left(\mathbf{B}+\mathbf{C}\right)=\mathbf{A}\mathbf{B} +\mathbf{A}\mathbf{C}$ 

* **Transpose of a Matrix**

$$\mathbf{A}^T =
   {\scriptsize\begin{pmatrix}
     a_{11} & a_{21} & \cdots & a_{m1}\\ 
     a_{12} & a_{22} & \ddots & a_{m2} \\ 
     \vdots & \ddots & \ddots & \vdots \\ 
     a_{1n} & a_{2n} & \cdots & a_{mn}
   \end{pmatrix}}$$

* **Properties of Transpose**

  $$
  \begin{aligned}
     \left(\mathbf{A}^T\right)^T &= \mathbf{A} \\ 
     \left(\mathbf{A} +\mathbf{B}\right)^T 
       &=\mathbf{A}^T +\mathbf{B}^T \\         
     \left(\mathbf{A}\mathbf{B}\right)^T
       &=\mathbf{B}^T\mathbf{A}^T \\ 
     \left(k\mathbf{A}\right)^T
      &=k\mathbf{A}^T
  \end{aligned}$$

* **Special Matrices**

  * In a **zero matrix**, $~$all entries are zeros
  
  * In a **triangular matrix**, $~$all entries above or below the main diagonal are zeros (lower triangular or upper triangular)
  
  * In a **diagonal matrix**, $~$all entries not on the main diagonal are zeros

  * A **scalar matrix** is a diagonal one where all entries on the main diagonal are equal.
    $~$If those entries are $1$'s, it is an **identity matrix**, $\mathbf{I}$ 
    (or $~\mathbf{I}_n$ when there is a need to emphasize the order of the matrix)
    
  * An $n \times n$ matrix $\mathbf{A}$ is **symmetric** $~$if $\mathbf{A}^T=\mathbf{A}$

